# Generated by Django 4.0.4 on 2023-08-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='titlu',
            new_name='title',
        ),
    ]
