# Generated by Django 4.0.4 on 2023-08-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_resources_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Resources'},
        ),
    ]
